spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plus
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

jwt:
  secret:
    key: asfda4ious5fa42fdgg25rdhag2r5a3vg45a3er84g34g6kjhgad84g1gr68g4